//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bachhoaxanhdemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idProduct { get; set; }
        public string productName { get; set; }
        public Nullable<double> productPrice { get; set; }
        public string tradeMark { get; set; }
        public string madeIn { get; set; }
        public string ingredient { get; set; }
        public string howToUse { get; set; }
        public Nullable<double> weight { get; set; }
        public string preservation { get; set; }
        public string decription { get; set; }
        public string image { get; set; }
        public Nullable<int> idProductTitle { get; set; }
    
        public virtual ProductTitle ProductTitle { get; set; }
    }
}
